#!/bin/bash
# AURA Relay - GitHub Push Script
# This script helps you push the project to GitHub

set -e

echo "🚀 AURA Relay - GitHub Push Instructions"
echo "=========================================="
echo ""
echo "The repository is ready to push but requires GitHub authentication."
echo ""
echo "OPTION 1: Using GitHub CLI (Recommended)"
echo "-----------------------------------------"
echo "1. Install gh: https://cli.github.com/"
echo "2. Run: gh auth login"
echo "3. Run: gh repo create aurarelay/aura-relay --public --source=. --remote=origin --push"
echo ""
echo "OPTION 2: Using Personal Access Token"
echo "--------------------------------------"
echo "1. Create token at: https://github.com/settings/tokens"
echo "   - Select scopes: repo, workflow"
echo "2. Run:"
echo "   git remote set-url origin https://YOUR_USERNAME:YOUR_TOKEN@github.com/AURA-Relay/aura-relay.git"
echo "   git push -u origin main"
echo ""
echo "OPTION 3: Using SSH Key"
echo "----------------------"
echo "1. Generate SSH key: ssh-keygen -t ed25519 -C \"your_email@example.com\""
echo "2. Add to GitHub: https://github.com/settings/keys"
echo "3. Run:"
echo "   git remote set-url origin git@github.com:AURA-Relay/aura-relay.git"
echo "   git push -u origin main"
echo ""
echo "OPTION 4: Manual Upload"
echo "----------------------"
echo "1. Create repository at: https://github.com/new"
echo "   - Name: aura-relay"
echo "   - Description: AURA Relay - Ask. Verify. Act."
echo "   - Visibility: Public"
echo "   - DO NOT initialize with README"
echo "2. Then run the commands shown below"
echo ""
echo "Current Repository Status:"
echo "=========================="
git status --short
echo ""
echo "Recent Commits:"
echo "==============="
git log --oneline -5
echo ""
echo "Ready to push commands (after authentication):"
echo "=============================================="
echo "git push -u origin main"
echo ""
echo "Or to create and push in one command with GitHub CLI:"
echo "gh repo create aurarelay/aura-relay --public --source=. --remote=origin --push"
echo ""
